name: Code Style

on: [pull_request_target]

jobs:
  fix-code-style:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}

      - name: Run php-cs-fixer
        uses: docker://oskarstark/php-cs-fixer-ga:3.0.0

      - name: Run prettier
        uses: actionsx/prettier@v2
        with:
          args: --write .

      - uses: stefanzweifel/git-auto-commit-action@v4.9.0
        with:
          commit_user_name: Markus Poerschke (Bot)
          commit_user_email: markus+githubbot@poerschke.nrw
          commit_message: Fix code style!
